# -*- coding: utf-8 -*-
"""titanic project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUCFj4uC-Ks-XeytyNVi1r3m28zlnB3p
"""

!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

df.head()

df.dtypes

df.dtypes[df.dtypes=='object']

df.dtypes[df.dtypes=='int']

#describe data frame
df.describe()

object_col=list(df.dtypes[df.dtypes=='object'].index)
object_col

df[object_col].describe()

df

df.info()

df['Name']

df[['Name','Sex']]

df.iloc[:8,:4]

list(df.columns)

df['Pclass']

df['Pclass'].nunique()

df['Sex']=='male'
df[df['Sex']=='male']

df[df['Fare']>=7.3]

df[(df['Sex'] == 'male') & (df['Fare'] >= 7.3)]

df['Sex'].value_counts()

df[(df['PassengerId'] > 100) & (df['Survived'] == 1)]

df[(df['Sex'] == 'male') & (df['Fare'] >= 7.3)]['Sex'].value_counts()

df[(df['Sex'] == 'female') & (df['Survived'] == 1)].value_counts()

conditions = [
    (df['Age'] <= 20),
    (df['Age'] > 20) & (df['Age'] <= 40),
    (df['Age'] > 40)
]

labels = ['Baby', 'Adult', 'Old']

df['Age_Category'] = np.select(conditions, labels, default='Nan')

print(df)

def Age_Sex_Combi(row):
    if row['Sex']=='female' and row['Age'] <20:
        return 'minor-female'
    elif row['Sex']=='male' and row['Age'] <20:
        return 'minor-male'
    elif row['Sex']=='female' and row['Age']>=20 and row['Age']<40:
        return 'adult-female'
    elif row['Sex']=='male' and row['Age']>=20 and row['Age']<40:
        return 'adult-male'
    elif row['Sex']=='female' and row['Age']>=40:
        return 'old-female'
    elif row['Sex']=='male' and row['Age']>=40:
        return 'old-male'
    else:
        return 'i don know'

df['Age_Sex_Combi']=df.apply(Age_Sex_Combi,axis=1)

df

df['Sum_PassengerId_Survived'] = df.apply(lambda row: row['PassengerId'] + row['Survived'], axis=1)
df

df_leng = len(df)
n_clmn = [1]*df_leng
df['santhi'] = n_clmn
df